#
# Makefile for gocv tracking
#
PROG=color
usage:
	@echo "usage: make [run]"

edit e:
	vi main.go

build b:
	go build -o $(PROG) main.go

run r:
	#./$(PROG)
	go run main.go

clean:
	rm -f $(PROG)

git-update gu:
	cd ..; make gu



