#
# Makefile for testing python opencv
#
PROG=camera-4

edit e:
	vi $(PROG).py

run-test rt:
	@echo "> make (run-test) [1|2|3]"
run-test-1 rt1:
	python3 camera-1.py
run-test-2 rt2:
	python3 camera-2.py
run-test-3 rt3:
	python3 camera-3.py
run-test-4 rt4:
	python3 camera-4.py



git-update gu:
	cd ..; make gu
