
usage:
	@echo "usage: make [run]"

run r:
	go run main.go
run-help rh:
	go run main.go -h


get-model gm:
	wget https://github.com/doleron/yolov5-opencv-cpp-python/raw/main/config_files/yolov5s.onnx -O ../assets/models/yolov5s.onnx
	wget https://github.com/pjreddie/darknet/blob/master/data/coco.names?raw=true -O ../assets/models


git-update gu:
	cd ..; make gu


