
usage:
	@echo "usage: make [run]"

run r:
	go run yolov3.go

run-tiny rt:
	go run yolov3.go -model=tiny

run-spp rs:
	go run yolov3.go -model=spp

run-help rh:
	go run yolov3.go -h


git-update gu:
	cd ..; make gu


